// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ourfwvlbeokoxfgftyrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91cmZ3dmxiZW9rb3hmZ2Z0eXJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDMzMDQsImV4cCI6MjA2NjQxOTMwNH0.5gPjpXrObYfiSzczuz1WgwiHmKMTwt5m3fTXs6qEkrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);